### ISSUE TITLE
Compatibility with big-endian architectures

### ISSUE THREAD

**Issue by pkubaj** [dreibh/socketapi#1]
I'm compiling socketapi on FreeBSD on powerpc64 and get an error at socketapi/tools.icc:79:
     79 #error BIG??

Is this software compatible with big-endian architectures?

**Comment by dreibh** [comment]
Yes, socketapi should be compatible with big-endian architectures as well. This is a bug. Could you test whether the latest commit (afeb56202fa44daddff64500f03785b490e11c12) solves the issue?

**Comment by pkubaj** [comment]
Yes, this commit fixes the problem.

**Comment by dreibh** [comment]
Great! The fix is now also included in the latest upstream release 2.2.17 (https://www.uni-due.de/~be0001/sctplib/).
